Repository ldcumg/first-sparta-open-source-library, pull requests merged in 2024-09, with the labels that each got.

#6 [refactor] AlertToast 분리
  src/App.jsx
  src/components/AlertToast.jsx
  src/components/ToastContainer.jsx
Labels: 리팩토링

#8 Docs
  README.md
  src/App.jsx
  src/components/AlertToast.jsx
  src/components/ToastContainer.jsx
  src/styles/tost.css
Labels: 문서 수정, 리팩토링

#7 [update] alert option 적용
  src/App.jsx
  src/components/AlertToast.jsx
  src/components/ToastContainer.jsx
Labels: 기능개발

#20 [refactor] tsconfig파일 추가
  .prettierrc
  package.json
  src/App.tsx
  src/assets/logo.jpeg
  src/components/AlertToast.tsx
  src/components/ConfirmToast.tsx
  src/components/ToastContainer.tsx
  src/main.jsx
  src/main.tsx
  src/utils/eventBus.ts
  src/utils/setPosition.ts
  src/utils/toast.ts
  tsconfig.json
  yarn.lock
Labels: 리팩토링, 구조변경

#24 update: 메인에 기본 세팅 가이드 추가
  src/App.tsx
  src/types/ToastType.ts
  src/utils/toast.ts
Labels: 문서 수정

#29 Refactor
  src/App.tsx
  src/components/AlertToast.tsx
  src/components/ConfirmToast.tsx
  src/components/ToastContainer.tsx
  src/types/ToastType.ts
  src/utils/toast.ts
Labels: 기능개발

#40 메인페이지 사진 크기 조정
  src/App.tsx
Labels: 스타일링
